name: Keep Aiven Database Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel & Aiven
        run: |
          curl -s -X GET "https://burnout-api.vercel.app/ping.php"
          echo "Ping berhasil dikirim pada $(date)"
